// <auto-generated />
namespace _LABELINSP_APPWEB.Migrations.ElectroluxPLV
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _6K : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6K));
        
        string IMigrationMetadata.Id
        {
            get { return "202010161349107_6K"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
