// <auto-generated />
namespace _MPPL_WEB_START.Migrations.ElectroluxPLV
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _157K : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_157K));
        
        string IMigrationMetadata.Id
        {
            get { return "202004251654314_157K"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
