// <auto-generated />
namespace _MPPL_WEB_START.Migrations.ElectroluxPLB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _27K : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27K));
        
        string IMigrationMetadata.Id
        {
            get { return "202008310649000_27K"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
