// <auto-generated />
namespace _MPPL_WEB_START.Migrations.WRP
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _19K : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_19K));
        
        string IMigrationMetadata.Id
        {
            get { return "202009142013563_19K"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
