// <auto-generated />
namespace _MPPL_WEB_START.Migrations.Grandhome
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2K : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2K));
        
        string IMigrationMetadata.Id
        {
            get { return "201911061634136_2K"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
