// <auto-generated />
namespace _MPPL_WEB_START.Migrations.ElectroluxPLS
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _5P : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5P));
        
        string IMigrationMetadata.Id
        {
            get { return "202008190335081_5P"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
