// <auto-generated />
namespace _MPPL_WEB_START.Migrations.Eldisy
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _17P : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17P));
        
        string IMigrationMetadata.Id
        {
            get { return "201806010731066_17P"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
