// <auto-generated />
namespace _MPPL_WEB_START.Migrations.Eldisy
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _25P : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25P));
        
        string IMigrationMetadata.Id
        {
            get { return "201806270536329_25P"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
